---
title: "Milankovich Cycles"
author: "Jason Yamada-Hanff"
date: "May 6, 2016"
output:
  html_document:
    fig_height: 4
    fig_width: 6
    keep_md: yes
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages}
# install required packages, if needed
required.packages <- c("tidyr", "dplyr", "zoo", "ggplot2", "gridExtra")
new.packages <- required.packages[!(required.packages %in% installed.packages()[,"Package"])]
if (length(new.packages)) install.packages(new.packages)

# load packages
library(tidyr)
library(dplyr)
library(zoo)
library(ggplot2)
library(gridExtra)
```

```{r insol-fn}
# from http://biocycle.atmos.colostate.edu/shiny/Milankovitch/#Qday.65N.solstice.R
Qday.65N.solstice <- function(S0=1367, eccentricity=0.0167,
                              obliquity=0.4091, perihelion=1.7963){

  # Given Earth's orbital parameters (eccentricity, obliquity, & perhihelion),
  # Calculate the daily mean top-of-atmosphere insolation at 65N June solstice

  # For a derivation see http://en.wikipedia.org/wiki/Insolation

  latitude <- 65. * pi / 180.
  Q.day <- S0*(1+eccentricity*sin(perihelion))^2 *sin(latitude)*sin(obliquity)

  return(Q.day)
}
```

## Orbital data

Data from Laskar, orbital parameters

```{r orbital-cycle-display}
# read Laskar simulated orbital parameters
milank <- read.table("INSOLN.LA2004.BTL.ASC.E.txt", col.names = c("time", "eccentricity", "obliquity", "precession"), header=FALSE);

# convert obliquity from radians to degrees
milank$obliquity_degree <- (180 / pi) * milank$obliquity;
# calculate precession "index"
milank$precession_index <- milank$eccentricity * sin(milank$precession);
# calculate mean daily insolation (W/m2) for 65*N latitude at summer solstice
milank$insolation <- Qday.65N.solstice(eccentricity = milank$eccentricity, obliquity = milank$obliquity, perihelion = milank$precession)

# display orbital parameters
milank %>%
  select(-obliquity, -precession, -insolation) %>%
  gather(var, value, eccentricity, obliquity_degree, precession_index) %>%
  ggplot() +
    geom_path(aes(x=time, y=value)) +
    facet_grid(var ~ ., scales="free_y") +
    xlim(-1e3, 0) + xlab("kiloyears before present");
```

## Display orbitral parameters with insolation

```{r orbital-display-with-insolation}
# display orbital parameters
milank.tidy <- select(milank, -obliquity, -precession) %>%
                 gather(var, value,
                        eccentricity, obliquity_degree,
                        precession_index, insolation);
milank.tidy$var <- factor(milank.tidy$var,
                            levels=c("eccentricity", "obliquity_degree",
                                     "precession_index", "insolation"))
ggplot(milank.tidy) +
    geom_path(aes(x=time, y=value)) +
    facet_grid(var ~ ., scales="free_y") +
    xlim(-1e3, 0) + xlab("kiloyears before present");
```

## Recovering frequencies of orbital parameters

```{r orbital-spectra}
# calculate frequency power spectra
ecc.spec <- spec.pgram(milank[,"eccentricity"], plot=FALSE);
obl.spec <- spec.pgram(milank[,"obliquity"],    plot=FALSE);
prc.spec <- spec.pgram(milank[,"precession"],   plot=FALSE);
ins.spec <- spec.pgram(milank[,"insolation"],   plot=FALSE);

# combine and display spectra
milank.spec.df <- data.frame(frequency = ecc.spec$freq,
                             eccentricity = ecc.spec$spec,
                             obliquity = obl.spec$spec,
                             precession = prc.spec$spec,
                             insolation = ins.spec$spec);

milank.spec.df <- gather(milank.spec.df, var, power,
                         eccentricity, obliquity, precession, insolation);
milank.spec.df$var <- factor(milank.spec.df$var,
                              levels=c("eccentricity", "obliquity",
                                       "precession", "insolation"));
ggplot(milank.spec.df) +
    geom_path(aes(x=frequency, y=power))   +
    facet_grid(var ~ ., scales = "free_y") +
    xlim(0, 0.3);
```

```{r insolation-display}
# freq domain plot
ins.spec.df <- data.frame(frequency = ins.spec$freq,
                          power     = ins.spec$spec);
p2 <- ggplot(ins.spec.df) +
        geom_path(aes(x=frequency, y=power)) +
        xlim(0, 0.1);

# time domain plot
p1 <- ggplot(milank) +
        geom_path(aes(x=time, y=insolation)) +
        xlim(-1e3, 0) +
        xlab("kiloyears before present") +
        ylab("W/m^2") +
        ggtitle("Mean daily insolation at 65*N lat, summer");
grid.arrange(p1, p2, nrow=2, ncol=1);
```

# Analyzing Vostok data

```{r vostok-deut-load}
# read Vostok deuterium data
deut <- read.table("deutnat.txt", skip=111, header=FALSE,
                    col.names = c("depth", "age", "deut", "deltaTS"));
ggplot(deut) + geom_path(aes(x=age, y=deut)) + ylab("Deuterium (heavy water) measure") +
               scale_x_reverse() + xlab("age (years before present)");
```

```{r insolation-and-vostok-deut}
# time domain plot
p1 <- ggplot(milank) +
        geom_path(aes(x=time, y=insolation)) +
        xlim(-450, 0) +
        xlab("kiloyears before present") +
        ylab("W/m^2") +
        ggtitle("Mean daily insolation at 65*N lat, summer");
p2 <- ggplot(deut) + geom_path(aes(x=age, y=deut)) +
        ylab("Deuterium (heavy water) measure") +
        scale_x_reverse(limits=c(450e3, 0)) + xlab("age (years before present)") +
        ggtitle("Vostok temperature proxy");
grid.arrange(p1, p2, nrow=2, ncol=1);
```

```{r vostok-deut-spec}
# fill in "missing" values to make regular intervals between points
deut.full <- na.spline(as.ts(zoo(deut$deut, order.by=deut$age)));
# calculate "periodogram"
deut.spec <- spec.pgram(deut.full, plot=FALSE);
```

```{r vostok-deut-spec-plot}
# plot
deut.spec.df <- data.frame(frequency = deut.spec$freq, spec = deut.spec$spec);
ggplot(deut.spec.df) + geom_path(aes(x=frequency, y=spec), color="black") +
                       xlim(0, 2e-4) + ylab("spectral power (arbitrary units)") +
                       geom_vline(aes(xintercept=1/100e3), color="blue", alpha=0.3) +
                       geom_vline(aes(xintercept=1/41e3), color="blue", alpha=0.3) +
                       geom_vline(aes(xintercept=1/23e3), color="blue", alpha=0.3) +
                       annotate("text", x=1/100e3, y=Inf, vjust=1, label="100") +
                       annotate("text", x=1/41e3,  y=Inf, vjust=1, label="41") +
                       annotate("text", x=1/23e3,  y=Inf, vjust=1, label="23 kyr");
```

## Vostok CO2 data

```{r vostok-co2}
co2nat <- read.table("co2nat.txt", skip=156, col.names = c("age", "co2"));
co2.full <- na.spline(as.ts(zoo(co2nat$co2, order.by=co2nat$age)));

ggplot(co2nat) +
  geom_path(aes(x=age, y=co2)) + scale_x_reverse();
```

```{r vostok-co2-spec}
co2.spec <- spec.pgram(co2.full, plot=FALSE);

co2.spec.df <- data.frame(frequency = co2.spec$freq, spec = co2.spec$spec);
ggplot(co2.spec.df) +
    geom_path(aes(x=frequency, y=spec), color="black") +
    xlim(0, 2e-4) + ylab("spectral power (arbitrary units)") +
    geom_vline(aes(xintercept=1/100e3), color="blue", alpha=0.3) +
    geom_vline(aes(xintercept=1/41e3), color="blue", alpha=0.3) +
    geom_vline(aes(xintercept=1/23e3), color="blue", alpha=0.3) +
    annotate("text", x=1/100e3, y=Inf, vjust=1, label="100") +
    annotate("text", x=1/41e3,  y=Inf, vjust=1, label="41") +
    annotate("text", x=1/23e3,  y=Inf, vjust=1, label="23 kyr");
```

## Lea et al, 2000 foraminifera data (watch sampling rate and units)

```{r lea2000}
tr163    <- read.table("tr16319l-tab.txt", comment.char = "#", header = TRUE, na.strings = "-999");
tr163.f  <- na.approx(as.ts(zoo(tr163$d18Ouvige, order.by=tr163$yrBP)));
tr163.df <- data.frame(d18O=tr163.f);
tr163.df$age <- seq(tr163$yrBP[1], tr163$yrBP[nrow(tr163)], length.out=length(tr163.f));

tr163.z  <- na.spline(zoo(tr163$d18Ouvige, order.by=tr163$yrBP));

tr163.spec <- spec.pgram(tr163.df$d18O, plot=FALSE);
p1 <- ggplot(tr163.df)                                   +
        geom_path(aes(x=age, y=d18O))                    +
        scale_x_reverse();

tr163.spec.df <- data.frame(frequency = tr163.spec$freq, spec = tr163.spec$spec);
p2 <- ggplot(tr163.spec.df) + geom_path(aes(x=frequency, y=spec), color="black")    +
                       xlim(0, 2e-4) + ylab("spectral power (arbitrary units)")     +
                       geom_vline(aes(xintercept=1/100e3), color="blue", alpha=0.3) +
                       geom_vline(aes(xintercept=1/41e3), color="blue", alpha=0.3)  +
                       geom_vline(aes(xintercept=1/23e3), color="blue", alpha=0.3)  +
                       annotate("text", x=1/100e3, y=Inf, vjust=1, label="100")     +
                       annotate("text", x=1/41e3,  y=Inf, vjust=1, label="41")      +
                       annotate("text", x=1/23e3,  y=Inf, vjust=1, label="23 kyr");
grid.arrange(p1, p2, nrow=2, ncol=1);
```

# Graphing Milankovich and climate spectra together

```{r}
p1 <- ggplot(ins.spec.df) +
        geom_path(aes(x=frequency, y=power)) +
        xlim(0, 0.1);

p2 <- ggplot(deut.spec.df) +
  geom_path(aes(x=frequency, y=spec), color="black") +
  xlim(0, 1e-4) +
  ylab("power (arbitrary units)");

grid.arrange(p1, p2, nrow=2, ncol=1)
```

# Looking back at Vostok deuterium data

```{r}
ggplot(deut) + geom_path(aes(x=age, y=deut)) +
    ylab("Deuterium (heavy water) measure") + scale_x_reverse() +
    xlab("age (years before present)");
```